name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
          python-version: '3.12'

      - name: Install Poetry
        run: |
          pip install poetry==2.2.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: docs/wkmigrate/yarn.lock # need to put the lockfile path explicitly

      - name: Install Dependencies
        run: |
          poetry source remove pypi-proxy 2>/dev/null || true
          poetry config repositories.pypi https://pypi.org/simple
          poetry install

      - name: Build Site
        run: make docs

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/wkmigrate/build

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
