name: integration

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    # Skip integration tests for PRs originating from external forks
    # (they cannot access repository secrets).
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pyVersion: ['3.12']

    env:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      AZURE_FACTORY_NAME: ${{ secrets.AZURE_FACTORY_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
          python-version: ${{ matrix.pyVersion }}

      - name: Install dependencies
        run: |
          pip install poetry==2.2.1
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
          poetry install

      - name: Run integration tests
        run: poetry run pytest -m integration --tb=short -v
