name: build

on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - main

permissions:
  id-token: write
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        pyVersion: [ '3.12' ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: ${{ matrix.pyVersion }}

      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78
        with:
          version: "0.8.4"
          enable-cache: true

      - name: Run unit tests
        run: |
          uv sync
          make test

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78
        with:
          version: "0.8.4"
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Format modules
        run: make fmt

      - name: Fail on differences
        run: git diff --exit-code

  docs:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.12'

      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78
        with:
          version: "0.8.4"
          enable-cache: true

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: "20.20.2"
          cache: yarn
          cache-dependency-path: docs/wkmigrate/yarn.lock

      - name: Install dependencies
        run: uv sync

      - name: Build website
        run: make docs
